# Generated by Django 4.1.7 on 2023-03-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
